CREATE DATABASE [Estudos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Estudos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Estudos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Estudos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Estudos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin EXEC [Estudos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Estudos] SET ANSI_NULL_DEFAULT OFF GO
ALTER DATABASE [Estudos] SET ANSI_NULLS OFF GO
ALTER DATABASE [Estudos] SET ANSI_PADDING OFF GO
ALTER DATABASE [Estudos] SET ANSI_WARNINGS OFF GO
ALTER DATABASE [Estudos] SET ARITHABORT OFF GO
ALTER DATABASE [Estudos] SET AUTO_CLOSE OFF GO
ALTER DATABASE [Estudos] SET AUTO_SHRINK OFF GO
ALTER DATABASE [Estudos] SET AUTO_UPDATE_STATISTICS ON GO
ALTER DATABASE [Estudos] SET CURSOR_CLOSE_ON_COMMIT OFF GO
ALTER DATABASE [Estudos] SET CURSOR_DEFAULT  GLOBAL GO
ALTER DATABASE [Estudos] SET CONCAT_NULL_YIELDS_NULL OFF GO
ALTER DATABASE [Estudos] SET NUMERIC_ROUNDABORT OFF GO
ALTER DATABASE [Estudos] SET QUOTED_IDENTIFIER OFF GO
ALTER DATABASE [Estudos] SET RECURSIVE_TRIGGERS OFF GO
ALTER DATABASE [Estudos] SET  DISABLE_BROKER GO
ALTER DATABASE [Estudos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF GO
ALTER DATABASE [Estudos] SET DATE_CORRELATION_OPTIMIZATION OFF GO
ALTER DATABASE [Estudos] SET TRUSTWORTHY OFF GO
ALTER DATABASE [Estudos] SET ALLOW_SNAPSHOT_ISOLATION OFF GO
ALTER DATABASE [Estudos] SET PARAMETERIZATION SIMPLE GO
ALTER DATABASE [Estudos] SET READ_COMMITTED_SNAPSHOT OFF GO
ALTER DATABASE [Estudos] SET HONOR_BROKER_PRIORITY OFF GO
ALTER DATABASE [Estudos] SET RECOVERY SIMPLE GO
ALTER DATABASE [Estudos] SET  MULTI_USER GO
ALTER DATABASE [Estudos] SET PAGE_VERIFY CHECKSUM  GO
ALTER DATABASE [Estudos] SET DB_CHAINING OFF GO
ALTER DATABASE [Estudos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) GO
ALTER DATABASE [Estudos] SET TARGET_RECOVERY_TIME = 60 SECONDS GO
ALTER DATABASE [Estudos] SET DELAYED_DURABILITY = DISABLED GO
ALTER DATABASE [Estudos] SET ACCELERATED_DATABASE_RECOVERY = OFF  GO
ALTER DATABASE [Estudos] SET QUERY_STORE = OFF GO
ALTER DATABASE [Estudos] SET  READ_WRITE GO